#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: set ft=python et sw=4 ts=8:


def main() -> None:
    return None


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
